title: PriceWaiter Developer Documentation
email: developers@pricewaiter.com
description: "Developer documentation for the PriceWaiter Name Your Price® extension."
baseurl: ""
url: "https://developer.pricewaiter.com"
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/New_York
exclude: [Gemfile, Gemfile.lock, README.md]

sass:
  sass_dir: _sass

kramdown:
  input: GFM
