# Site title and subtitle. This is used in _includes/header.html
title: 'PriceWaiter Developer Documentation'
subtitle: 'Documentation'

footer: 'PriceWaiter'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1
safe: true
gems:
  - jekyll-redirect-from
  - jekyll-coffeescript

# URL to source code, used in _includes/footer.html
codeurl: 'https://docs.pricewaiter.com'

# Default categories (in order) to appear in the navigation
sections: [
    ['widget', 'Documentation'],
    ['api', 'Reference'],
    ['platforms', 'Platforms'],
    ['conversion', 'Conversion Tracking'],
    ['misc', 'Extra Functionality'],
]

collections:
  widget:
  api:
  platforms:
    output: true
  misc:
    output: true
  conversion:
    output: true

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['README.md', 'Gemfile*','vendor']

sass:
    style: :compressed
