# Site title and subtitle. This is used in _includes/header.html
title: 'PriceWaiter Developer Documentation'
subtitle: 'Name Your Price<sup>®</sup> Extension Documentation'

footer: 'PriceWaiter'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://www.pricewaiter.com'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['ref', 'Reference'],
    ['dwn', 'Other Documentation']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['vendor','bin', 'README.md','deploy.sh','node_modules','Gemfile*']

# Use the kramdown Markdown renderer
markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true

#Site Vars
doc_row: 'row'

doc_col_light: 'column column-light'

doc_col_dark: 'column column-dark'
