sections:
- name: apiKey
  description: PriceWaiter requires ALL widget users to have a custom API key for each store. The Name Your Price button and widget will not work without a valid key.
  options:
  - name: apiKey
    type: string
    required: true
    description: Your API key, available at the top of this page
    values: n/a
    default: none
- name: button
  description: Control the look and feel of the Name Your Price button on your website.
  options:
  - name: type
    type: string
    required: false
    description: Controls the style and text of button injected into the page.<br />nyp is a "Name Your Price" button and mo is a "Make An Offer" button.
    values: "'button_nyp', 'button_mo', 'text_nyp', 'text_mo'"
    default: button_nyp
  - name: color
    type: string
    required: false
    description: The background color used for the ''button'' type or the text color used for the ''text'' type.
    values: hexadecimal code
    default: "#97C0E6"
  - name: hoverColor
    type: string
    required: false
    description: The hover state background color for ''button'' or the text color hover state for the ''text'' type.
    values: hexadecimal code
    default: "#6D9FD6"
  - name: buttonTextColor
    type: string
    required: false
    description: The color used for the text and icon of the ''button'' type. The currently accepted values are ''white'' or ''black''.
    values: hexadecimal code
    default: (Best value based on color)
  - name: buttonTextHoverColor
    type: string
    required: false
    description: The color used for the text and icon of the ''button'' type in its hover state. The currently accepted values are ''white'' or ''black''.
    values: hexadecimal code
    default: (Best value based on hoverColor)
  - name: size
    type: string
    required: false
    description: "The size and dimensions of the button depending on which 'type' you are using.<br />button + lg: 160x140<br />button + sm: 140x28<br />text + lg: 160x20<br />text + sm140x14"
    values: "'sm' or 'lg'"
    default: lg
- name: product
  description: "Set information about the product the user is viewing. If your product has options such as color, size, etc. You should look at the <a href=\"/docs/api/\">API Methods</a> and learn how to tell the PriceWaiter widget that the user has selected specific product options."
  options:
  - name: sku
    type: string
    required: true
    description: "The SKU or Manufacturer's Part Number (MPN) for the product."
    values: n/a
    default: none
  - name: name
    type: string
    required: true
    description: "The product's name, e.g. <i>Apple iPhone 64GB</i>"
    values: n/a
    default: none
  - name: description
    type: string
    required: false
    description: "A brief description of the product."
    values: n/a
    default: none
  - name: price
    type: decimal
    required: false
    description: "Your price for the product."
    values: n/a
    default: none
  - name: image
    type: string
    required: false
    description: "The full URL (including http://) to an image for the product. Images will be scaled down to fit within an box approximately 200x200 pixels. Accepts .jpg, .png, or .gif image formats."
    values: n/a
    default: none
- name: user
  description: "Optionally, you can pass information about the current user if they are logged into your system. This will pre-populate their name and email address accordingly in the widget."
  options:
  - name: name
    type: string
    required: false
    description: "The current user's full name."
    values: n/a
    default: none
  - name: email
    type: string
    required: false
    description: "The current user's email address."
    values: n/a
    default: none
- name: quantity
  description: "Set the default quantity value and/or disable the quantity field."
  options:
  - name: quantity
    type: integer
    required: false
    description: "Default value of the quantity field."
    values:
    default: 1
  - name: hide_quantity_field
    type: bool
    required: false
    description: "Hide the quantity field. The default value is still submitted."
    values: "'true' or 'false'"
    default: false
- name: onLoad
  description: "Since PriceWaiter is loaded asynchronously, it might not be available right when you start setting up your page. By adding a hook in here, you can update PriceWaiter when, for example, the user changes the product configuration."
  options:
  - name: onLoad
    type: function
    required: false
    description: "A custom function you can specify to be executed once PriceWaiter is loaded."
    values: n/a
    default: none
- name: onProductOptionsRequired
  description: "If you have used <strong>setProductOptionRequired</strong> to mark a product option as required, this callback is fired when the user clicks the Name Your Price button without supplying all required product options. If not specified, PriceWaiter will use <strong>window.alert()</strong> to prompt the user to provide all the missing options."
  options:
  - name: onProductOptionsRequired
    type: function
    required: false
    description: "A custom function you can specify to be executed when the user clicks the 'Name Your Price' button without selecting all required product options."
    values: n/a
    default: none